title: Emircan Kılınç
description: Software Developer and Engineer
baseurl: ""
url: "https://emircankilinc.github.io"

author:
  name: Emircan Kılınç
  email: emircankilinc@gmail.com

# Sosyal medya bağlantıları
social_media:
  github: https://github.com/emircankilinc
  linkedin: https://www.linkedin.com/in/emircankilinc
  email: emircankilinc@gmail.com

# CV Bilgileri
owner: Emircan Kılınç
email: emircankilinc@gmail.com
phone: +49 1783132615
address: 12555 Berlin, Germany

# Diğer ayarlar...
